import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('a tutor builds in the wizard, revisits and resumes activities, then sees the saved lesson summary', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('link', { name: 'Build a lesson', exact: true }).click();
  await expect(page.locator('#wizardProgress')).toContainText('Step 1 of 4');
  await page.locator('#wizardContinue').click();
  await expect(page.locator('#builderStatus')).toBeVisible();
  await expect(page.locator('#builderStatus')).toContainText('learner');
  await page.getByLabel('Learner label (initials or code)').fill('Q01');
  await page.getByRole('button', { name: 'Add student' }).click();
  await page.getByLabel('Template name').fill('Tutor walkthrough');
  await page.locator('#wizardContinue').click();
  await page.locator('[data-concept-id="l1-digraphs"]').check();
  await page.locator('#wizardContinue').click();
  await page.getByLabel('Practice activity').selectOption('sound-boxes');
  await page.getByLabel('Response mode').selectOption('paper');
  await page.getByLabel('Activity item selection').selectOption('ship');
  await page.getByRole('button', { name: 'Add step', exact: true }).click();
  await page.getByLabel('Practice activity').selectOption('whats-missing-cards');
  await page.getByLabel('Number of cards').fill('1');
  await page.getByLabel('Missing letter position').selectOption('first');
  await page.getByRole('button', { name: 'Add step', exact: true }).click();
  await page.locator('#wizardContinue').click();
  await page.locator('#wizardBack').click();
  await expect(page.locator('#wizardProgress')).toContainText('Step 3 of 4');
  await page.locator('#wizardContinue').click();
  await expect(page.locator('#lessonReview')).toContainText('Q01');
  await expect(page.locator('#lessonReview')).toContainText('Sound Boxes');
  await page.setViewportSize({ width: 390, height: 844 });
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Start lesson', exact: true }).click();
  await page.getByRole('button', { name: 'Reveal written word' }).click();
  await page.getByRole('button', { name: 'Independent', exact: true }).click();
  await page.getByRole('button', { name: 'Finish word and continue' }).click();
  await page.locator('#lessonToolbar').getByRole('button', { name: 'Finish step' }).click();
  await expect(page.getByLabel('Number of cards')).toHaveValue('1');
  await expect(page.getByLabel('Number of cards')).toBeDisabled();
  await page.locator('#lessonToolbar').getByRole('button', { name: 'Back', exact: true }).click();
  await expect(page.locator('#lessonToolbar')).toContainText('Previously completed');
  await page.locator('#lessonToolbar').getByRole('button', { name: 'Next', exact: true }).click();
  await page.locator('#lessonToolbar').getByText('Lesson options', { exact: true }).click();
  await page.getByRole('link', { name: 'Review lesson plan' }).click();
  await expect(page.getByRole('button', { name: 'Start lesson', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Resume lesson · Tutor walkthrough' }).click();
  await page.getByRole('button', { name: 'Go to Letter Review' }).click();
  await page.getByRole('button', { name: 'Start Exercise' }).click();
  await page.getByRole('button', { name: 'Right', exact: true }).click();
  await page.getByRole('button', { name: 'Next Card' }).click();
  await expect(page.getByRole('heading', { name: 'Final stats' })).toBeVisible();
  await page.locator('#lessonToolbar').getByRole('button', { name: 'Finish step' }).click();
  await expect(page.locator('#builderStatus')).toContainText('Lesson complete: 2 of 2');
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('bright-steps-student-progress')));
  expect(saved.sessions.filter(item => item.activity === 'lesson')).toHaveLength(1);
  expect(saved.sessions.filter(item => item.activity === 'sound-boxes')).toHaveLength(1);
  expect(await page.evaluate(() => sessionStorage.getItem('bright-steps-active-lesson'))).toBeNull();
  expect(errors).toEqual([]);
});
